{% set name = "RAPIDpy" %}
{% set version = "2.6.0" %}
{% set sha256 = "39f7ffaf52359105181f40db55720d0dcf428e006650c6ecde5dca7ece1be640" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - future
    - gdal
    - netcdf4
    - numpy
    - pandas
    - pangaea
    - pyproj
    - python-dateutil
    - pytz
    - requests
    - rtree
    - shapely
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - RAPIDpy
    - RAPIDpy.rapid
    - RAPIDpy.dataset
    - RAPIDpy.postprocess
    - RAPIDpy.postprocess.generate_return_periods
    - RAPIDpy.postprocess.generate_seasonal_averages
    - RAPIDpy.inflow
    - RAPIDpy.inflow.lsm_rapid_process
    - RAPIDpy.inflow.CreateInflowFileFromERAInterimRunoff
    - RAPIDpy.inflow.CreateInflowFileFromLDASRunoff
    - RAPIDpy.inflow.CreateInflowFileFromWRFHydroRunoff
    - RAPIDpy.gis
    - RAPIDpy.gis.centroid
    - RAPIDpy.gis.muskingum
    - RAPIDpy.gis.network
    - RAPIDpy.gis.taudem
    - RAPIDpy.gis.weight
    - RAPIDpy.gis.workflow
    - RAPIDpy.postprocess
    - RAPIDpy.postprocess.generate_return_periods
    - RAPIDpy.postprocess.generate_seasonal_averages
    - RAPIDpy.postprocess.goodness_of_fit
    - RAPIDpy.postprocess.merge

about:
  home: http://github.com/erdc-cm/RAPIDpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A python interface for the RAPID program (rapid-hub.org).'
  description: |
    RAPIDpy is a python interface for RAPID that assists to prepare inputs,
    runs the RAPID program, and provides post-processing utilities.
    More information about installation and the input parameters for RAPID
     can be found at http://rapid-hub.org.
  doc_url: http://rapidpy.readthedocs.io
  dev_url: https://github.com/erdc-cm/RAPIDpy

extra:
  recipe-maintainers:
    - snowman2
    - swainn
    - mgeheran
